### ISSUE TITLE
/clubs gives too much info?

### ISSUE THREAD

**Issue by hesa** [hesa/tranarappen#84] opened 2016-06-20 23:08 UTC
https://app.tranarappen.se/api/0.0.0//clubs/

GIves, for me, too much information. The following info would suffice:

{"offset":0,"count":4,"items":[{"uuid":"f9d39cc2-cb7f-4ab0-b31a-5c0355596abe","created":"2016-04-26T22:10:15.77165Z", "name":"AS Roma"}  etc etc etc

That is, I suggest we skip members, and especially videos

**Comment by jonkri** [comment] 2016-06-30 15:50
@hesa: Could you please remind me what the issue is here, and why you are using the clubs endpoint?

**Comment by jonkri** [comment] 2016-07-16 12:29
@hesa: Ping! :)

**Comment by jonkri** [comment] 2016-07-17 14:17
I'm closing this issue, as this endpoint doesn't exist anymore.

**Closed** 2016-07-17 14:18 UTC
Labels: question, server
